"""Statistical feature callables shared by numpy and torch extractors."""

from __future__ import annotations

import numpy as np

from fedot_ind.core.operation.transformation.representation.statistical.stat_features import (
    autocorrelation,
    ben_corr,
    crest_factor,
    energy,
    hjorth_complexity,
    hjorth_mobility,
    hurst_exponent,
    interquartile_range,
    kurtosis,
    mean_ema,
    mean_moving_median,
    mean_ptp_distance,
    n_peaks,
    pfd,
    ptp_amp,
    q5,
    q25,
    q75,
    q95,
    shannon_entropy,
    skewness,
    slope,
    zero_crossing_rate,
)
from fedot_ind.core.operation.transformation.torch_backend.statistical.stat_features import (
    autocorrelation_torch,
    ben_corr_torch,
    crest_factor_torch,
    energy_torch,
    hjorth_complexity_torch,
    hjorth_mobility_torch,
    hurst_exponent_torch,
    interquantile_range_torch,
    kurtosis_torch,
    max_torch,
    mean_ema_torch,
    mean_moving_median_torch,
    mean_ptp_distance_torch,
    mean_torch,
    median_torch,
    min_torch,
    n_peaks_torch,
    pfd_torch,
    ptp_amp_torch,
    q5_torch,
    q25_torch,
    q75_torch,
    q95_torch,
    shannon_entropy_torch,
    skewness_torch,
    slope_torch,
    std_torch,
    zero_crossing_rate_torch,
)


STAT_METHODS = {
    "mean_": np.mean,
    "median_": np.median,
    "std_": np.std,
    "max_": np.max,
    "min_": np.min,
    "q5_": q5,
    "q25_": q25,
    "q75_": q75,
    "q95_": q95,
}

STAT_METHODS_TORCH = {
    "mean_": mean_torch,
    "median_": median_torch,
    "std_": std_torch,
    "max_": max_torch,
    "min_": min_torch,
    "q5_": q5_torch,
    "q25_": q25_torch,
    "q75_": q75_torch,
    "q95_": q95_torch,
}

STAT_METHODS_GLOBAL = {
    "skewness_": skewness,
    "kurtosis_": kurtosis,
    "n_peaks_": n_peaks,
    "slope_": slope,
    "ben_corr_": ben_corr,
    "interquartile_range_": interquartile_range,
    "energy_": energy,
    "cross_rate_": zero_crossing_rate,
    "autocorrelation_": autocorrelation,
    "shannon_entropy_": shannon_entropy,
    "ptp_amplitude_": ptp_amp,
    "mean_ptp_distance_": mean_ptp_distance,
    "crest_factor_": crest_factor,
    "mean_ema_": mean_ema,
    "mean_moving_median_": mean_moving_median,
    "hjorth_mobility_": hjorth_mobility,
    "hjorth_complexity_": hjorth_complexity,
    "hurst_exponent_": hurst_exponent,
    "petrosian_fractal_dimension_": pfd,
}

STAT_METHODS_GLOBAL_TORCH = {
    "skewness_": skewness_torch,
    "kurtosis_": kurtosis_torch,
    "n_peaks_": n_peaks_torch,
    "slope_": slope_torch,
    "ben_corr_": ben_corr_torch,
    "interquartile_range_": interquantile_range_torch,
    "energy_": energy_torch,
    "cross_rate_": zero_crossing_rate_torch,
    "autocorrelation_": autocorrelation_torch,
    "shannon_entropy_": shannon_entropy_torch,
    "ptp_amplitude_": ptp_amp_torch,
    "mean_ptp_distance_": mean_ptp_distance_torch,
    "crest_factor_": crest_factor_torch,
    "mean_ema_": mean_ema_torch,
    "mean_moving_median_": mean_moving_median_torch,
    "hjorth_mobility_": hjorth_mobility_torch,
    "hjorth_complexity_": hjorth_complexity_torch,
    "hurst_exponent_": hurst_exponent_torch,
    "petrosian_fractal_dimension_": pfd_torch,
}

__all__ = [
    "STAT_METHODS",
    "STAT_METHODS_GLOBAL",
    "STAT_METHODS_GLOBAL_TORCH",
    "STAT_METHODS_TORCH",
]
