coverage:
  status:
    project:
      default:
        threshold: 5%
    patch: false

ignore:
    - "fedot_ind/__init__.py"
    - "fedot_ind/core/tuning/search_space.py"
    - "fedot_ind/core/repository/model_repository.py"
    - "fedot_ind/core/repository/constanst_repository.py"