"""Industrial evolutionary optimisation contracts."""

from fedot_ind.core.optimizer.configuration import (
    EVOLUTION_CONFIG_SCHEMA,
    EvolutionConfig,
    EvolutionConfigError,
    ExecutionPolicy,
    MutationAgentType,
    MutationStrategy,
    ResourceBudget,
    normalize_evolution_config,
)
from fedot_ind.core.optimizer.domain import (
    CandidateFailure,
    EvaluationOutcome,
    EvolutionPhase,
    EvolutionState,
    IndustrialPopulationError,
    transition_evolution_state,
)
from fedot_ind.core.optimizer.observability import (
    CandidateRejectionReason,
    CandidateStatus,
    EvaluationStatus,
    EvolutionDiagnosticsRecorder,
    EvolutionDiagnosticsSnapshot,
    EvolutionSummary,
    build_evolution_summary,
    write_evolution_diagnostics,
)
from fedot_ind.core.optimizer.graph_validation import (
    ComputeDevice,
    GRAPH_SPEC_SCHEMA,
    GRAPH_VALIDATION_SCHEMA,
    GraphNodeSpec,
    GraphSpec,
    IndustrialGraphVerifier,
    NodePosition,
    OperationCapabilities,
    OperationKind,
    ValidationIssue,
    ValidationIssueCode,
    ValidationReport,
    ValidationSeverity,
    validate_graph,
)

__all__ = [
    "EVOLUTION_CONFIG_SCHEMA",
    "ComputeDevice",
    "GRAPH_SPEC_SCHEMA",
    "GRAPH_VALIDATION_SCHEMA",
    "CandidateFailure",
    "CandidateRejectionReason",
    "CandidateStatus",
    "EvaluationOutcome",
    "EvaluationStatus",
    "EvolutionConfig",
    "EvolutionConfigError",
    "EvolutionDiagnosticsRecorder",
    "EvolutionDiagnosticsSnapshot",
    "EvolutionPhase",
    "EvolutionState",
    "EvolutionSummary",
    "GraphNodeSpec",
    "GraphSpec",
    "IndustrialGraphVerifier",
    "ExecutionPolicy",
    "IndustrialPopulationError",
    "MutationAgentType",
    "MutationStrategy",
    "NodePosition",
    "OperationCapabilities",
    "OperationKind",
    "ResourceBudget",
    "ValidationIssue",
    "ValidationIssueCode",
    "ValidationReport",
    "ValidationSeverity",
    "build_evolution_summary",
    "normalize_evolution_config",
    "transition_evolution_state",
    "validate_graph",
    "write_evolution_diagnostics",
]
