from __future__ import annotations

from fedot_ind.core.kernel_learning.generators.base import (
    DEFAULT_GENERATOR_NAMES,
    KernelFeatureGeneratorMixin,
    OperationSpec,
    call_transform,
    features_to_fedot_input_data,
    load_operation_class,
    normalize_feature_matrix,
    normalize_time_series_tensor,
    operation_params,
    resolve_torch_device,
    to_fedot_input_data,
    to_numpy,
    to_torch,
    unwrap_operation_output,
)
from fedot_ind.core.kernel_learning.generators.lightweight import (
    IdentityFeatureGenerator,
    RandomProjectionEmbeddingFeatureGenerator,
    ShapeletFeatureGenerator,
    even_positions,
    min_shapelet_distance,
)
from fedot_ind.core.kernel_learning.generators.registry import (
    build_generator_registry,
    create_feature_generator,
    extend_with_legacy_pipeline_generators,
    resolve_generator_operation_specs,
)
from fedot_ind.core.kernel_learning.generators.repository import (
    BudgetedRepositoryFeatureGeneratorAdapter,
    GeneratorBudgetPolicy,
    PipelineFeatureGeneratorAdapter,
    RepositoryFeatureGeneratorAdapter,
    SummaryFeatureGenerator,
    build_lightweight_fallback,
)
from fedot_ind.core.kernel_learning.generators.specs import (
    BASIS_ONLY_GENERATORS,
    eigen_spec,
    fourier_spec,
    recurrence_spec,
    riemann_spec,
    tabular_spec,
    topological_spec,
    torch_quantile_spec,
    wavelet_spec,
)

__all__ = [
    "BASIS_ONLY_GENERATORS",
    "BudgetedRepositoryFeatureGeneratorAdapter",
    "DEFAULT_GENERATOR_NAMES",
    "GeneratorBudgetPolicy",
    "IdentityFeatureGenerator",
    "KernelFeatureGeneratorMixin",
    "OperationSpec",
    "PipelineFeatureGeneratorAdapter",
    "RandomProjectionEmbeddingFeatureGenerator",
    "RepositoryFeatureGeneratorAdapter",
    "ShapeletFeatureGenerator",
    "SummaryFeatureGenerator",
    "build_generator_registry",
    "build_lightweight_fallback",
    "call_transform",
    "create_feature_generator",
    "eigen_spec",
    "even_positions",
    "extend_with_legacy_pipeline_generators",
    "features_to_fedot_input_data",
    "fourier_spec",
    "load_operation_class",
    "min_shapelet_distance",
    "normalize_feature_matrix",
    "normalize_time_series_tensor",
    "operation_params",
    "recurrence_spec",
    "resolve_generator_operation_specs",
    "resolve_torch_device",
    "riemann_spec",
    "tabular_spec",
    "to_fedot_input_data",
    "to_numpy",
    "to_torch",
    "topological_spec",
    "torch_quantile_spec",
    "unwrap_operation_output",
    "wavelet_spec",
]
