@startuml
'https://plantuml.com/sequence-diagram

class AtomizedModel {
    Enum
}

abstract TEMPORARY_EXCLUDED
abstract FEDOT_PREPROC_MODEL
abstract INDUSTRIAL_CLF_PREPROC_MODEL
abstract NEURAL_MODELS
abstract FORECASTING_PREPROC
abstract INDUSTRIAL_PREPROC_MODEL
abstract SKLEARN_CLF_MODELS
abstract SKLEARN_REG_MODELS
abstract FORECASTING_MODELS


INDUSTRIAL_CLF_PREPROC_MODEL --> AtomizedModel
AtomizedModel <-- SKLEARN_CLF_MODELS
FEDOT_PREPROC_MODEL --> AtomizedModel
AtomizedModel <- INDUSTRIAL_PREPROC_MODEL
SKLEARN_REG_MODELS --> AtomizedModel
AtomizedModel <-- FORECASTING_MODELS
FORECASTING_PREPROC -> AtomizedModel
NEURAL_MODELS -> AtomizedModel

abstract TEMPORARY_EXCLUDED {
LinearClassFSImplementation,
NonLinearClassFSImplementation,
FastICAImplementation,
PolyFeaturesImplementation,
ExogDataTransformationImplementation,
OneHotEncodingImplementation,
LabelEncodingImplementation
DummyOperation,
FeatureFilter,
SignalExtractor,
IsolationForestClassImplementation,
IsolationForestRegImplementation,
ChronosExtractor,
RiemannExtractor,
GradientBoostingRegressor,
RandomForestRegressor,
AdaBoostRegressor,
SklearnLinReg,
FedotKnnRegImplementation,
SklearnMultinomialNB,
FedotKnnClassImplementation
OmniScaleModel,
TSTModel,
XCModel
}

abstract FEDOT_PREPROC_MODEL {
ScalingImplementation,
NormalizationImplementation,
ImputationImplementation,
KernelPCAImplementation,
TopologicalFeaturesImplementation
}

abstract INDUSTRIAL_CLF_PREPROC_MODEL {
DecomposerClassImplementation,
ResampleImplementation,
}

abstract NEURAL_MODELS {
InceptionTimeModel,
OmniScaleModel,
ResNetModel,
TSTModel,
XCModel
}

abstract FORECASTING_PREPROC {
LaggedTransformationImplementation,
SparseLaggedTransformationImplementation,
TsSmoothingImplementation,
GaussianFilterImplementation,
ExogDataTransformationImplementation,
}

abstract INDUSTRIAL_PREPROC_MODEL {
ChannelCentroidFilter,
EigenBasisImplementation,
WaveletBasisImplementation,
FourierBasisImplementation,
RecurrenceExtractor,
QuantileExtractor,
RiemannExtractor,
TopologicalFeaturesImplementation,
MiniRocketExtractor,
ChronosExtractor,
IsolationForestClassImplementation,
IsolationForestRegImplementation,
}

abstract SKLEARN_CLF_MODELS {
GradientBoostingClassifier,
SklearnLogReg,
DecisionTreeClassifier,
RandomForestClassifier,
MLPClassifier
}

abstract SKLEARN_REG_MODELS {
XGBRegressor,
SklearnSGD,
ExtraTreesRegressor,
SklearnRidgeReg,
SklearnLassoReg,
DecisionTreeRegressor
}

abstract FORECASTING_MODELS {
AutoRegImplementation,
STLForecastARIMAImplementation,
ExpSmoothingImplementation,
CGRUImplementation,
GLMIndustrial
}

@enduml
