name: Integration Tests

on:
  schedule:
    - cron: '0 12 * * 3'
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv package manager
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create and activate virtualenv
        run: |
          uv venv .venv
          source .venv/bin/activate

      - name: Install dependencies with uv
        run: |
          uv pip install --upgrade pip
          uv pip install -e .
          uv pip install pytest pytest-cov

      - name: Run tests
        run: pytest --cov=fedot_ind tests/integration --cov-report=xml -vvv

      - name: Codecov-coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: integrationtests
